"""add_bets_table

Revision ID: ace3989e0174
Revises: 6bb3702c3bd4
Create Date: 2025-06-30 23:19:18.745214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ace3989e0174'
down_revision: Union[str, None] = '6bb3702c3bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('market_name', sa.String(length=255), nullable=False, comment="Ex: 'Vencedor do Jogo', 'Mais/Menos 2.5 Golos'"),
    sa.Column('selection', sa.String(length=255), nullable=False, comment="Ex: 'Flamengo', 'Mais de 2.5'"),
    sa.Column('odds', sa.Float(), nullable=False, comment='As odds (cotação) no momento da aposta'),
    sa.Column('stake', sa.Float(), nullable=False, comment='O valor apostado (unidades ou monetário)'),
    sa.Column('status', sa.Enum('PENDING', 'WON', 'LOST', 'VOID', name='betstatus'), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True, comment='Data em que a aposta foi resolvida'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bets_id'), 'bets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bets_id'), table_name='bets')
    op.drop_table('bets')
    # ### end Alembic commands ###
