"""add_analysis_and_tip_columns_to_games_table

Revision ID: ce2b2f4f4dcb
Revises: 2ba5fe73b3a1
Create Date: 2025-06-19 20:34:10.719356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce2b2f4f4dcb'
down_revision: Union[str, None] = '2ba5fe73b3a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('analysis', sa.Text(), nullable=True, comment='Análise descritiva e o que esperar do jogo.'))
    op.add_column('games', sa.Column('value_bet_tip', sa.Text(), nullable=True, comment='Dica de aposta de valor (+EV) identificada.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'value_bet_tip')
    op.drop_column('games', 'analysis')
    # ### end Alembic commands ###
